-- FROZEN. Do not edit this file to make it pass.
--
-- 정수님, 2026-09-10: *"그 언어 API 에 대고 사용자들이 자기 함수를 얹어서 설정하거나
-- 플러그인, 워크플로 등을 만들면, 하위호환을 엄격하게 지켜야 합니다."*
--
-- This is what a user's script written against the v1 API is allowed to do. It
-- runs in CI on every commit, so renaming a binding, changing an argument
-- order, or making a previously-optional argument required breaks the build
-- rather than someone's plugin.
--
-- Widening the API means adding `v2.lua` next to this file. It never means
-- editing this one — a compatibility check you may edit to make it pass is not
-- a check. If a change genuinely cannot keep v1 working, that is a real
-- decision to make in the open, and deleting this file is how you make it.

local name = "api-v1-" .. tostring(os.time())

-- Every binding exists and is callable. Checked by name because a script in the
-- wild reaches for these by name.
for _, fn in ipairs({ "attach", "capture", "click", "insert", "key", "ls", "new", "send", "sleep" }) do
  assert(type(remuda[fn]) == "function", "remuda." .. fn .. " is gone")
end

-- ls() takes no arguments and returns rows with these fields.
local before = remuda.ls()
assert(type(before) == "table", "ls must return a table")

-- new(name) defaults the command to the user's shell; new(name, argv) takes a
-- list. Both spellings are v1.
remuda.new(name, { "sh" })

local found = nil
for _, row in ipairs(remuda.ls()) do
  if row.name == name then found = row end
end
assert(found, "ls did not show the session new() made")
assert(type(found.alive) == "boolean", "row.alive")
assert(type(found.idle) == "number", "row.idle")
assert(type(found.cols) == "number" and type(found.rows) == "number", "row size")

-- send(name, text) delivers a line with Enter appended.
remuda.send(name, "echo $((6*7))-v1")

local function wait_for(needle)
  for _ = 1, 200 do
    local screen = remuda.capture(name)
    assert(type(screen) == "string", "capture must return a string")
    if screen:find(needle, 1, true) then return screen end
    remuda.sleep(0.05)
  end
  error("never saw " .. needle)
end

wait_for("42-v1")

-- insert(name, bytes) appends nothing, so this sits at the prompt un-submitted.
remuda.insert(name, "echo $((8*8))-v1")
-- key(name, spec) in Emacs `kbd` notation. RET is what submits the line above,
-- which is also the proof that insert did not submit it itself.
remuda.key(name, "RET")
wait_for("64-v1")

-- click(name, col, row) defaults to the left button; a fourth argument names
-- another. A shell ignores mouse reports, so this checks the call shape, not an
-- effect — the effect is checked in the Rust suite against a program that reads
-- them.
remuda.click(name, 1, 1)
remuda.click(name, 2, 2, "right")

-- A refusal is raised, never returned as nil. A script that pcall's a bad
-- session must keep getting an error.
local ok = pcall(function() return remuda.capture("no-such-session-v1") end)
assert(not ok, "a missing session must raise, not return nothing")

local ok2 = pcall(function() return remuda.key(name, "no-such-key") end)
assert(not ok2, "an unknown key must raise, not send an empty burst")

print("v1 ok")
