-- FROZEN. Do not edit this file to make it pass.
--
-- v3 adds lifecycle-managed, in-process reloads. `_activate_module` is an
-- internal loader helper and must stay off the public remuda table.

assert(type(remuda.reload) == "function", "remuda.reload is gone")
assert(remuda._activate_module == nil, "the module activator must remain internal")

local phase = rawget(_G, "api_v3_phase")
if phase == nil then
  local missing = "api-v3-missing-" .. tostring(os.time())
  local ok, err = pcall(remuda.reload, missing)
  assert(not ok, "reloading a missing mod must raise")
  assert(tostring(err):find("no such package", 1, true), tostring(err))
elseif phase == "same_version" then
  remuda.reload("sample")
  remuda.emit("probe")
  assert(remuda.tools.sample_status() == "11", "same-version reload must retain state")
elseif phase == "migration" then
  remuda.reload("sample")
  remuda.emit("probe")
  assert(remuda.tools.sample_status() == "131", "reload must migrate the prior state")
elseif phase == "migration_failure" then
  local ok = pcall(remuda.reload, "sample")
  assert(not ok, "a failing migration must raise")
  remuda.emit("probe")
  assert(remuda.tools.sample_status() == "151", "failed migration must preserve active code and state")
elseif phase == "legacy_refusal" then
  local ok, err = pcall(remuda.reload, "sample")
  assert(not ok, "legacy mod reload must be refused")
  assert(tostring(err):find("legacy entry format", 1, true), tostring(err))
  assert(remuda.tools.sample_status() == "171", "legacy refusal must leave the active module alone")
else
  error("unknown API v3 test phase: " .. tostring(phase))
end

print("v3 ok")
